sudo: false

language: node_js

os:
  - linux
  # - osx

node_js:
  - 9
  - 8
  - 7

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  - yarn test

after_success:
  # Publish the coverage report to Coveralls
  - cat coverage/lcov.info | node_modules/.bin/coveralls

notifications:
  email: false
